version: '3.6'

services:

  php:
    build:
      context: docker
      dockerfile: php.docker
    user: 1000:1000
    environment:
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - '.:/app'

  nginx:
    image: nginx:alpine
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/app'
    ports:
      - '8080:80'
    depends_on:
      - php

  mysql:
    image: 'mariadb:10.4'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - '33061:3306'

  redis:
    image: 'redis:5.0-alpine'
    volumes:
      - 'redis:/data'
    ports:
      - '63791:6379'

volumes:
  mysql:
    name: '${APP_NAME}-mysql'
  redis:
    name: '${APP_NAME}-redis'
  composer-cache:
    name: composer-cache
