#!/usr/bin/env bash

if [[ ! -f .env ]]; then
    cp .env.example .env
    echo .env.example copied to .env
fi
source .env

PS1='\[\033[1;32m\]D \[\033[1;33m\]\u@\h \[\033[1;34m\]\w \[\033[1;35m\]# \[\033[0m\]'

operation=$1 && shift
[[ -z $operation ]] && exit

case "$operation" in
    "composer" )
        docker-compose run --rm php composer "$@" ;;

    "artisan" )
        docker-compose run --rm php ./artisan "$@" ;;

    "tinker" )
        docker-compose run --rm -u 0000 php ./artisan tinker "$@" ;;

    "test" )
        docker-compose run --rm php vendor/bin/phpunit "$@";;

    "shell" )
        docker-compose run --rm -u 0000 -e PS1="$PS1" "$1" ash ;;

    "up" )
        docker-compose up -d ;;

    "down" )
        docker-compose down ;;

    "build" )
        docker build -f ./docker/php.docker ./docker --tag "${APP_NAME}_php" ;;

    * )
        echo "Notexisten command"
esac
